### ISSUE TITLE
Manual Installation Steps

### ISSUE THREAD

**Issue by michaelbrant** [chromium-for-lambda/chromium-binaries#21]
"For manual installation, download the zip file containing Chromium and it's required dependencies and upload to Lambda yourself."

Can someone elaborate on this? Steps would be really appreciated!

**Comment by stephankaag** [comment]
I assume the uploading to AWS is the unclear part?

There are multiple ways. Are you entirely new to the AWS ecosystem?

**Comment by stephankaag** [comment]
> I'm familiar with AWS, but I need a little more guidance. Which zip file exactly? I see a few in the release. And then is this a lambda layer? How do I import it from the function?
> 
> Thank you so much!
> 
> Also, the reason I want to install manually is because I want this function to run as quickly as possible and so I don't want to have to call install() when the function is invoked.

It's not a layer. The releases contain just the binary files and required dependencies.

The `chrome-*.zip` file is needed when you want to use the 'new' headless mode.
The `headless_shell*.zip` is needed when you want to use the traditional (old) headless mode.
The other (bigger) zip file contains the raw build output.

To package the browser together with your function you will have to compress quite a bit. I expect that at most you can get the headless_shell variant small enough.

Let me know if this works! I will experiment with compression myself.

**Comment by michaelbrant** [comment]
Thanks for the info! Do you think the old version would be good enough if I just need it to take screenshots? 
If you are able to get it working with the manual installation and can send over steps that would be really appreciated!

**Comment by stephankaag** [comment]
> Thanks for the info! Do you think the old version would be good enough if I just need it to take screenshots? If you are able to get it working with the manual installation and can send over steps that would be really appreciated!

Yep! Old version would be enough.

I've just updated the [README](https://github.com/chromium-for-lambda/chromium-binaries?tab=readme-ov-file#installation-via-a-lambda-layer) with instructions how to use the binaries with a layer.

Let me know if it's clear and if it worked!

**Comment by stephankaag** [comment]
Is that helpful @michaelbrant?

**Comment by michaelbrant** [comment]
thanks so much! I haven't had the chance to try it but I really appreciate you taking the time to do this.
