### ISSUE TITLE
Having Problems Targeting Older Chromium Versions

### ISSUE THREAD

**Issue by fvcpinheiro** [chromium-for-lambda/chromium-binaries#39]
I'm trying to target chromium version [123](https://github.com/chromium-for-lambda/chromium-binaries/releases/tag/arm64-amazon-linux-2-chromium-123.0.6312). How should I setup PLAYWRIGHT_CHROMIUM_DOWNLOAD_HOST environment variable with? I tried several approaches but it seems to keep failing.
Removing that env at all, it defaults to a azure host, but doesn't work as well.

I have the following dependencies for my project, running on an AWS Lambda nodejs 18 runtime environment.
```
{
  "name": "nodejs_lambdas",
  "dependencies": {
    "playwright-core": "1.42.1",
    "puppeteer-core": "22.6.5"
  }
}
```

Thanks!

**Comment by stephankaag** [comment]
Are you using Puppeteer or Playwright? What's the point of including them both?

**Comment by fvcpinheiro** [comment]
Trying to use Playwright. 
Puppeteer + sparticuz/chromium is what we currently use, but it unfortunately it doesn't support ARM. So that's why I came across this project.

**Comment by stephankaag** [comment]
You can remove puppeteer-core from your dependencies file.

The value for `PLAYWRIGHT_CHROMIUM_DOWNLOAD_HOST` should be `https://files.chromiumforlambda.org/amazon-linux-2/arm64` in your case. Please provide more information if that doesn't work as expected.

**Comment by fvcpinheiro** [comment]
Thanks for your help. 
I changed to use puppeteer 22.8.2 and it worked just fine! Was having some issues using playwright.
