### ISSUE TITLE
Why disable V8_HAS_PKU_JIT_WRITE_PROTECT?

### ISSUE THREAD

**Issue by bluenoah1991** [chromium-for-lambda/chromium-binaries#8]
Why disable V8_HAS_PKU_JIT_WRITE_PROTECT?

**Comment by stephankaag** [comment]
[It's only disabled Amazon Linux 2](https://github.com/chromium-for-lambda/chromium-binaries/blob/bdaa3655c8ebc9dc240e12a371bf7b7197f33b15/.github/actions/compile/action.yml#L28), on Amazon Linux 2023 it's enabled as usual. Don't remember the exact reason but I probably ran into errors on AL2.
